// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnpOVhhnhNhFLPMkPfhUx-cFxd2vz7fPA',
    appId: '1:1015518667902:web:2dcb7e6ae380fa6238642f',
    messagingSenderId: '1015518667902',
    projectId: 'igarchu',
    authDomain: 'igarchu.firebaseapp.com',
    storageBucket: 'igarchu.appspot.com',
    measurementId: 'G-T4HM5BPPT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnk43vCdoeyCdWE2MNJEoGlNOTjKo2wAg',
    appId: '1:1015518667902:android:fa93cec75facacdc38642f',
    messagingSenderId: '1015518667902',
    projectId: 'igarchu',
    storageBucket: 'igarchu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA45ZTAU3Eq5575zYl6FmBCtUIZtR3y20s',
    appId: '1:1015518667902:ios:521c5d3569fb2a8738642f',
    messagingSenderId: '1015518667902',
    projectId: 'igarchu',
    storageBucket: 'igarchu.appspot.com',
    iosClientId: '1015518667902-hq2vq1lrm9opmt7oak7qkj6vq0dqkuvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.iGarchu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA45ZTAU3Eq5575zYl6FmBCtUIZtR3y20s',
    appId: '1:1015518667902:ios:521c5d3569fb2a8738642f',
    messagingSenderId: '1015518667902',
    projectId: 'igarchu',
    storageBucket: 'igarchu.appspot.com',
    iosClientId: '1015518667902-hq2vq1lrm9opmt7oak7qkj6vq0dqkuvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.iGarchu',
  );
}
